---
- name: Converge
  hosts: all

  vars:
    dirsrv_suffix: "dc=test,dc=local"

    dirsrv_rootdn: "cn=Directory Manager"
    dirsrv_rootdn_password: "P455W0RD"

    dirsrv_serverid: "test"
    dirsrv_listen_host: 0.0.0.0

    dirsrv_tls_enabled: false

    dirsrv_password_storage_scheme: "PBKDF2_SHA256"
    dirsrv_install_examples: true
    dirsrv_ldapi_enabled: true

    dirsrv_plugins_enabled:
      MemberOf Plugin: true
      Distributed Numeric Assignment Plugin: true

    dirsrv_custom_schema:
      - "98telegram.ldif"

    # Interoperability between 389DS 1.3.X and 1.4.X
    dirsrv_defaults_version: "001004002"
    dirsrv_selfsigned_cert: False
    dirsrv_create_suffix_entry: True

  tasks:
    - name: Apply local lvps.389ds_server role
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../.."

    - name: Ensure container entries exist, for testing
      community.general.ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "cn=Directory Manager"
        bind_pw: "secret"
        dn: "{{ item.dn }}"
        objectClass: "{{ item.objectClass }}"
        state: present
      loop:
        - { dn: "ou=Groups,dc=example,dc=local", objectClass: ["organizationalunit", "top"] }
        - { dn: "ou=People,dc=example,dc=local", objectClass: ["organizationalunit", "top"] }
      register: dirsrv_test_containers
      failed_when: dirsrv_test_containers.changed
