---
dependency:
  name: galaxy
driver:
  name: docker
role_name_check: 1
platforms:
  # Images that contain the string "SYSCTL" will be trated with the "docker systemctl replacement" script
  - name: CentOS8-Other-SYSCTL
    image: centos:8
    python_package: python3
    python_devel_package: python3-devel
    install_epel: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  inventory:
    host_vars:
      CentOS8-Other-SYSCTL:
        # Use the Python 3 interpreter installed for this CentOS 8 platform.
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
