---
dependency:
  name: galaxy
driver:
  name: docker
role_name_check: 1
platforms:
  # Images that contain the string "SYSCTL" run systemd as PID 1.
  - name: CentOS8-Other
    image: centos:8
    python_package: python3
    python_devel_package: python3-devel
    install_epel: true
    command: /sbin/init
    user: root
    capabilities: []
    security_opts:
      - no-new-privileges
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
provisioner:
  name: ansible
  inventory:
    host_vars:
      CentOS8-Other:
        # Use the Python 3 interpreter installed for this CentOS 8 platform.
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
