---
- name: Converge
  hosts: all

  vars:
    dirsrv_suffix: "dc=test,dc=local"

    dirsrv_rootdn: "cn=Directory Manager"
    dirsrv_rootdn_password: "P455W0RD"
    dirsrv_listen_host: 0.0.0.0

    # Ansible is not secure enough for a SSF of 256 for 389DS 1.4.X
    # Unfortunately we don't yet have access to dirsrv_legacy or the installed version so we need to base the condition on the CentOS version
    dirsrv_tls_minssf: "128"

    dirsrv_tls_enabled: true
    dirsrv_tls_enforced: true
    dirsrv_tls_files_remote: false
    dirsrv_tls_certificate_trusted: false

    dirsrv_tls_cert_file: tls_test_local_cert.pem
    dirsrv_tls_key_file: tls_test_local.key

    dirsrv_create_suffix_entry: True

  tasks:
    - name: Apply local lvps.389ds_server role
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../.."

    - name: Ensure we can access the server, for testing
      community.general.ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=config"
        objectClass: "top"
        start_tls: "{{ dirsrv_tls_enabled }}"
        validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
        state: present

    - name: Test TLS enforcement
      block:
        - name: Ensure TLS is enforced
          community.general.ldap_entry:
            server_uri: "ldap://localhost"
            bind_dn: "{{ dirsrv_rootdn }}"
            bind_pw: "{{ dirsrv_rootdn_password }}"
            dn: "{{ dirsrv_suffix }}"
            objectClass: "domain"
            start_tls: "false"
            state: present
          register: dirsrv_tls_test

      rescue:
        - name: Assert that task failed successfully
          ansible.builtin.assert:
            that:
              - "'Minimum SSF not met.' in dirsrv_tls_test.details"
