---
- name: Converge
  hosts: all

  vars:
    dirsrv_rootdn_password: "P455W0RD"
    dirsrv_listen_host: 0.0.0.0

    dirsrv_tls_enabled: true
    dirsrv_tls_enforced: true
    dirsrv_tls_files_remote: false
    dirsrv_tls_certificate_trusted: false

    dirsrv_tls_cert_file: tls_test_local_cert.pem
    dirsrv_tls_key_file: tls_test_local.key

    dirsrv_create_suffix_entry: True
  pre_tasks:
    - name: Create dirsrv service dropin directory
      ansible.builtin.file:
        path: /etc/systemd/system/dirsrv@.service.d/
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: Copy dirsrv service dropin config
      become: true
      ansible.builtin.copy:
        src: dirsrv-dropin.conf
        dest: /etc/systemd/system/dirsrv@.service.d/custom.conf
        owner: root
        group: root
        mode: '0644'
        force: true

    # Ansible is not secure enough for a SSF of 256 for 389DS 1.4.X
    # Unfortunately we don't yet have access to dirsrv_legacy or the installed version so we need to base the condition on the CentOS version
    - name: Set minimum SSF
      ansible.builtin.set_fact:
        dirsrv_tls_minssf: "{%if ansible_facts['distribution_major_version'] | int == 8 %}128{% else %}256{% endif %}"

  roles:
    - role: lvps.389ds_server

  tasks:
    - name: Ensure we can access the server, for testing
      community.general.ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=config"
        objectClass: "top"
        start_tls: "{{ dirsrv_tls_enabled }}"
        validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
        state: present

    - name: Test TLS enforcement
      block:
        - name: Ensure TLS is enforced
          community.general.ldap_entry:
            server_uri: "ldap://localhost"
            bind_dn: "{{ dirsrv_rootdn }}"
            bind_pw: "{{ dirsrv_rootdn_password }}"
            dn: "{{ dirsrv_suffix }}"
            objectClass: "domain"
            start_tls: "false"
            state: present
          register: dirsrv_tls_test

      rescue:
        - name: Assert that task failed successfully
          ansible.builtin.assert:
            that:
              - "{{ dirsrv_tls_test.details }}.info == 'Minimum SSF not met.'"
