---
- name: Converge
  hosts: all

  vars:
    dirsrv_rootdn_password: "P455W0RD"
    dirsrv_listen_host: 0.0.0.0

    # BACKWARDS COMPATIBILITY TEST
    # Should guarantee nteroperability between 389DS 1.3.X and 1.4.X
    dirsrv_defaults_version: "001004002"
    dirsrv_selfsigned_cert: False
    dirsrv_create_suffix_entry: True

  tasks:
    - name: Apply local lvps.389ds_server role
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../.."

    - name: Ensure we can access the server, for testing
      community.general.ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=config"
        objectClass: "top"
        start_tls: "{{ dirsrv_tls_enabled }}"
        validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
        state: present

    - name: Ensure suffix entry exists
      community.general.ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "{{ dirsrv_suffix }}"
        objectClass: "domain"
        start_tls: "{{ dirsrv_tls_enabled }}"
        validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
        state: present
      register: dirsrv_suffix_test
      failed_when: dirsrv_suffix_test.changed

    # A complementary test (that asserts that the certificate *does* exist) has been placed in the default test.
    # The purpose of that test is one of a coal-mine canary: if RH changes the dn of the certificate the tests
    # fail and we notice it, and can change the dn we check against accordingly rather than havin a silent fail.
    - name: Ensure no self-signed certificate has been created
      ansible.builtin.shell:
        cmd: >
          set -o pipefail && \
            grep -rhsc 'CN=ssca.389ds.example.com,O=testing' /etc/dirsrv/slapd-{{ dirsrv_serverid }}/ | sort -r | uniq | head -n 1
        executable: /bin/bash
      register: dirsrv_selfsigned_cert_test
      failed_when: "dirsrv_selfsigned_cert_test.stdout | int > 0"
      changed_when: false

    - name: Ensure TLS is disabled
      community.general.ldap_attrs:
        server_uri: "ldap://localhost"
        validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
        start_tls: "{{ dirsrv_tls_enabled }}"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=config"
        attributes:
          nsslapd-security: "off"
        state: exact
      register: dirsrv_backwards_tls_test
      failed_when: dirsrv_backwards_tls_test.changed
