---
dependency:
  name: galaxy
driver:
  name: docker
role_name_check: 1
platforms:
  # Images that contain the string "SYSCTL" will be trated with the "docker systemctl replacement" script
  - name: CentOS8-Backwards-SYSCTL
    image: centos:8
    python_package: python2
    python_devel_package: python2-devel
    install_epel: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  inventory:
    host_vars:
      CentOS8-Backwards-SYSCTL:
        # This legacy scenario installs Python 2.7. Ansible Core 2.16 supports
        # it, whereas the CentOS 8 platform Python 3.6 cannot run its modules.
        ansible_python_interpreter: /usr/bin/python2
verifier:
  name: testinfra
