---
- name: Converge
  hosts: all

  vars:
    # Minimum default configuration
    dirsrv_rootdn_password: "P455W0RD"
    dirsrv_listen_host: 0.0.0.0

  pre_tasks:
    - name: Create dirsrv service dropin directory
      ansible.builtin.file:
        path: /etc/systemd/system/dirsrv@.service.d/
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: Copy dirsrv service dropin config
      become: true
      ansible.builtin.copy:
        src: dirsrv-dropin.conf
        dest: /etc/systemd/system/dirsrv@.service.d/custom.conf
        owner: root
        group: root
        mode: '0644'
        force: true

  roles:
    - role: lvps.389ds_server

  tasks:
    - name: Ensure we can access the server, for testing
      community.general.ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=config"
        objectClass: "top"
        start_tls: "{{ dirsrv_tls_enabled }}"
        validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
        state: present

    - name: Ensure self-signed certificate has been created
      ansible.builtin.shell:
        cmd: >
          set -o pipefail && \
            grep -rhsc 'CN=ssca.389ds.example.com,O=testing' /etc/dirsrv/slapd-{{ dirsrv_serverid }}/ | sort -r | uniq | head -n 1
        executable: /bin/bash
      register: dirsrv_selfsigned_cert_test
      failed_when: "dirsrv_selfsigned_cert_test.stdout | int == 0"
      changed_when: false
      when: not dirsrv_legacy
