---
- name: Converge
  hosts: all

  vars:
    dirsrv_serverid: default
    dirsrv_rootdn: cn=Directory Manager
    dirsrv_tls_enabled: false
    dirsrv_selfsigned_cert: true

    # Minimum default configuration
    dirsrv_rootdn_password: "P455W0RD"
    dirsrv_listen_host: 0.0.0.0

  tasks:
    - name: Apply local lvps.389ds_server role
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../.."

    - name: Ensure we can access the server, for testing
      community.general.ldap_entry:
        server_uri: "ldap://localhost"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=config"
        objectClass: "top"
        start_tls: "{{ dirsrv_tls_enabled }}"
        validate_certs: "{{ dirsrv_tls_certificate_trusted | default(false) }}"
        state: present

    - name: Ensure self-signed certificate has been created
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          certutil -L \
            -d /etc/dirsrv/slapd-{{ dirsrv_serverid }}/ \
            -n Self-Signed-CA \
            -f /etc/dirsrv/slapd-{{ dirsrv_serverid }}/pwdfile.txt >/dev/null
          certutil -L \
            -d /etc/dirsrv/slapd-{{ dirsrv_serverid }}/ \
            -n Server-Cert \
            -f /etc/dirsrv/slapd-{{ dirsrv_serverid }}/pwdfile.txt >/dev/null
        executable: /bin/bash
      register: dirsrv_selfsigned_cert_test
      failed_when: dirsrv_selfsigned_cert_test.rc != 0
      changed_when: false
      when: dirsrv_selfsigned_cert | default(false) | bool
